### ISSUE TITLE
b.O is not a function when accessing oauth2 loggin page

### ISSUE THREAD

**Issue by encodojoel** [DevExpress/testcafe-hammerhead#2434]
### What is your Scenario?

I'm working on a customer project using oauth2 for authentication.
The customer recently decided to implement e2e tests using testcafe.
 
### What is the current behavior?
When the tests try to access the oauth2 login page, instead of the actual page, an error is displayed, with the following message:
`This page has an error. You might just need to refresh it. Action failed: c:controller$doInit [b.O is not a function] Failing descriptor: {c:c:controller$doInit}`
 
### What is the Expected behavior?
Instead of the error, the actual page should be displayed.
 
### Your Environment details:
* node.js version:                    v14.5.0
* browser name and version:  firefox: 80.0, chrome 84.0.4147.135
* platform and version:          Windows 10.0.19041 Build 19041

## Other
While testing, I tried to execute the test manually within testcafe-hammerhead and went back in time until I found a commit that introduced this behavior.
This behavior was introduced in #1793 (commit: b9308cc1df644942f14899284aa17f00928a684d)
In this commit, the ternary condition was replaced, and the two branches have been swapped; but if I revert the two branches into their original state, then the issue is no longer reproducible, and I can't find any errors within other sites.

**Comment by wentwrong** [comment]
You mentioned that you figured out the exact commit that caused this bug. Do I understand it correctly that your site opens without errors when you use hammerhead with a version below than `14.3.1` (e.g. `14.3.0`)?
 
Could you please run TestCafe with the [--dev](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#--dev) flag and send us a screenshot of the DevTools console?
 
A reproducible example would also help if you can create one. In addition, you can send your private details to support@devexpress.com and attach a written confirmation that permits DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes.

**Comment by encodojoel** [comment]
Yes, I tested the website using 14.3.0, and it is working as expected.

Screenshot of DevTools when running with `--dev`:
![grafik](https://user-images.githubusercontent.com/70764935/92470579-eece1500-f1d6-11ea-891e-a5d1d3742165.png)

Same site, without testcafe:
![grafik](https://user-images.githubusercontent.com/70764935/92470859-56846000-f1d7-11ea-9b55-fd62bce7705e.png)

I'm currently working with my manager, in order to get permission from our customer to share the site with devexpress.

**Comment by Farfurix** [comment]
@encodojoel

Hello,

Thank you for the information. We'll wait for your update.

**Comment by encodojoel** [comment]
I've received confirmation from our customer to share our systems information.
I've just sent you an email to support@devexpress.com containing more informations.

**Comment by AlexSkorkin** [comment]
Thank you for sharing this information. One last step: we also need written approval from the entity that owns the server/web resource in order to access it for research/testing/debugging purposes.

**Comment by wentwrong** [comment]
We received a written confirmation and the URL of the OAuth2 page by e-mail and reproduced this error. Our team will investigate this issue and let you know once we have any results.

**Comment by encodojoel** [comment]
@AndreyBelym, I noticed you've updated the issue recently. Is there any additional detail we could provide you to help resolve that issue?
I just had planing for our next release, and our customer quite heavily requests this one.

**Comment by arubtsov** [comment]
Hi @encodojoel, There are no updates yet.

**Comment by encodojoel** [comment]
Sorry for the slightly unrelated question; however, this just came up in another meeting, when this issue was mentioned.
We noticed the product "TestCafe Studio Pro" and were wondering if the "DevExpress Technical Support" would help us in any way.

Our customer wouldn't be opposed to buying the product; however, we want to confirm, if there is an actual benefit for our project.

**Comment by Farfurix** [comment]
@encodojoel 

Hello,

There's no doubt that issues coming from paid customers have a higher priority than issues received from the open source community. However, this does not guarantee that every edge case issue must be fixed. We consider many factors: the complexity of the issue, the amount of resources it takes to get it fixed, the value we bring to the product after fixing it, etc.

As for your particular case, we created a PR: https://github.com/DevExpress/testcafe-hammerhead/pull/2578.
