### PR TITLE
fix `b.O is not a function when accessing oauth2 loggin page` (close #2434)

### LINKED ISSUE #2434: b.O is not a function when accessing oauth2 loggin page
### What is your Scenario?

I'm working on a customer project using oauth2 for authentication.
The customer recently decided to implement e2e tests using testcafe.
 
### What is the current behavior?
When the tests try to access the oauth2 login page, instead of the actual page, an error is displayed, with the following message:
`This page has an error. You might just need to refresh it. Action failed: c:controller$doInit [b.O is not a function] Failing descriptor: {c:c:controller$doInit}`
 
### What is the Expected behavior?
Instead of the error, the actual page should be displayed.
 
### Your Environment details:
* node.js version:                    v14.5.0
* browser name and version:  firefox: 80.0, chrome 84.0.4147.135
* platform and version:          Windows 10.0.19041 Build 19041

## Other
While testing, I tried to execute the test manually within testcafe-hammerhead and went back in time until I found a commit that introduced this behavior.
This behavior was introduced in #1793 (commit: b9308cc1df644942f14899284aa17f00928a684d)
In this commit, the ternary condition was replaced, and the two branches have been swapped; but if I revert the two branches into their original state, then the issue is no longer reproducible, and I can't find any errors within other sites.

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

**Review by miherlosev — APPROVED** [review]

**Review by Farfurix — APPROVED** [review]

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest-all

**Comment by LavrovArtem** [comment]
https://github.com/DevExpress/testcafe-hammerhead/pull/2578

**Comment by LavrovArtem** [comment]
https://github.com/DevExpress/testcafe-hammerhead/pull/2580
